- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
Stop including ref_counted.h from the Chromium base library, which
includes some headers making the ARM build fail, and is not necessary in
the first place.
Note that the rtc::RefCounted type is from the RTC base, not the
Chromium base.
> Remove extra Chromium header failing ARM build

- docs/manual/helloworld-unity-importwebrtc.md
I think there is an inconsistency on the documentation regarding the configuration of the Microsoft.MixedReality.WebRTC.Native.dll on the Unity inspector:
On Getting started->Unity tutorial->Importing MixedReality->WebRTC->Configuring the import settings the first picture shows on "Exclude Platforms" the WSAPlayer **checked ** for Win32/x86_64 library but later on the following table there is nothing written on "Exclude Platforms" for the same library:
> Added the exclusion of WSAPlayer platform on Win32 plugin docs

- README.md
The links to the Manual, Unity Tutorial, and API reference returned 404 pages so I updated them.
> Fixed 404 links in Readme Documentation section

- examples/TestAppUwp/Microsoft.MixedReality.WebRTC.TestAppUWP.csproj
- examples/TestAppUwp/Package.appxmanifest
- tools/ci/ci-cs.yaml
- tools/ci/templates/jobs-cs.yaml
Avoid build breaks in TestAppUWP by compiling it during the CI builds of the C# library.
Build both the Debug and Release configs, the former using the managed .NET Standard 2.0 framework while the later uses the .NET Native toolchain.
Disable signing the resulting AppX, as this is just a sample app and no signing key is committed to the repository for security reasons by policy.
> Build TestAppUWP during C# CI

- libs/Microsoft.MixedReality.WebRTC.Native/include/api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/sdp_utils.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/sdp_utils.h
- libs/Microsoft.MixedReality.WebRTC.Native/test/sdp_utils_tests.cpp
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Allow the caller to specify a semicolon-separated list of key=value
pairs of codec arguments passed directly to the preferred codec during
SDP filtering, to configure it.
This is a low-level interface for advanced use only, will no validation
checks whatsoever. This fixes #51 at least short term.
> Add codec parameter override to SDP filtering

- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.UWP.ARM.nuspec
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.UWP.x64.nuspec
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.UWP.x86.nuspec
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.ARM.Debug.props
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.ARM.Release.props
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x64.Debug.props
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x64.Release.props
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x86.Debug.props
- libs/Microsoft.MixedReality.WebRTC.Native.Core/Microsoft.MixedReality.WebRTC.Native.Core.WinRT.x86.Release.props
WebRtc is consumed via the webrtc.lib
Fixes #87
> Remove packaging of Org.WebRtc.dll

- libs/Microsoft.MixedReality.WebRTC.Native/include/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Mitigates https://github.com/webrtc-uwp/webrtc-uwp-sdk/issues/210.
TODO this is dependent on https://github.com/webrtc-uwp/webrtc-windows/pull/73
> Expose workaround for H.264 Hololens encoder bug

- libs/Microsoft.MixedReality.WebRTC.Native/include/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
This backport changes the original code due to some link error on Desktop.
Making a PR for it, then that change will be forward-ported to `master` to fix the same issue there.
> Backport #132 HL1 frame height workaround

- examples/TestAppUwp/MainPage.xaml
- examples/TestAppUwp/MainPage.xaml.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- Add support for setting extra parameters on local codecs. Since there seems to
be no easier way, we filter remote SDP messages before delivery.
- Allow endpoints which receive offers to filter codecs/request codec parameters
to the counterpart (before this change, only endpoints creating an offer did
SDP filtering).
Note that we now filter outgoing SDP answers as well as offers. Before this
change, we didn't filter answers, because removing codecs from an answer without
removing them from the corresponding offer left the connection in an
inconsistent state (e.g. A sends an offer to B with VP8 and H264; B internally
chooses VP8, replies with both codecs, but the answer is filtered to remove VP8;
A gets the filtered answer and chooses H264). Now we use the same filter on
incoming offers …
> Improve the codec filtering mechanism

- docs/manual/building-core.md
- docs/manual/building.md
Fix folder name: backslash to dot
- From `Microsoft.MixedReality.WebRTC\Unity.Examples\` to `Microsoft.MixedReality.WebRTC.Unity.Examples\`
Fix wrong folder name
- From `SimpleVideoChat` to `VideoChatDemo`
Minor markdown lint
- MD032/blanks-around-lists: Lists should be surrounded by blank linesmarkdownlint(MD032)
> Fix docs WebRTC.Unity.Examples directory

- examples/TestAppUwp/MainPage.xaml.cs
- libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/test/data_channel_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/peer_connection_test_helpers.h
- libs/Microsoft.MixedReality.WebRTC.Native/test/peer_connection_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Editor/EditorTests.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/DataChannelTests.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTests.cs
Make `mrsSetRemoteDescriptionAsync()` invoke a callback on completion, and change the signature of C# methods to be async. This allows the caller to know when the remote description has been applied, which informs that it is safe to call `CreateAnswer()`. Otherwise the call setting the remote
description may race against the call creating the answer, preventing the answer from being created if the remote description was not applied yet.
Rename all related methods and functions with the "async" suffix for readability and to force a breaking change and avoid silently ignoring the async task, which was an error in existing code.
> Async SetRemoteDescription to avoid race condition

- libs/Microsoft.MixedReality.WebRTC.Native/include/external_video_track_source_interop.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/external_video_track_source_interop.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source_impl.h
- libs/Microsoft.MixedReality.WebRTC.Native/test/external_video_track_source_tests.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/ExternalVideoTrackSourceInterop.cs
Split creation of external video tracks into 2 steps, the first creating the track object, and the second finalizing the creation and starting the track source capture.
In the current state of the API, the frame callbacks are owned by the peer connection, so there is little difference. However with the upcoming change adding standalone track objects, this change allows the user to register a frame callback before capture starts, and therefore be able to honor any frame request from the first one, while also keeping the WebRTC restriction that track sources must start in the capturing state.
This is only a breaking change if directly using the low-level C interop API. The C# library and Unity integration are not affected, as they will handle the change internally and transparently for the …
> 2-step external video track creation for callbacks

- libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/utils.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj.filters
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj.filters
- libs/Microsoft.MixedReality.WebRTC.Native/test/video_track_tests.cpp
Make `GlobalFactory` thread-safe to initialize and shutdown by using reference counting.
Previously `RemoveObject()` was attempting to destroy the `GlobalFactory` singleton instance as soon as the number of tracked objects alive reached zero. This was problematic for two reasons:
1. If thread A retrieves a pointer to the singleton before thread B, then thread B creates a new wrapper (which calls `AddObject()`) but later fails to complete the initializing of that object and has to destroy it before thread A itself added an object, then `RemoveObject()` (called from the wrapper destructor) will find no object alive and will destroy the `GlobalFactory` singleton instance, which leaves thread A with a dangling pointer.
2. Destroying the singleton instance was done outside the lock, and access …
> Make GlobalFactory thread-safe to initialize

- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/external_video_track_source_interop.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/external_video_track_source_impl.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/local_video_track.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/local_video_track.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/tracked_object.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/tracked_object.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj.filters
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj.filters
Simplify and clean-up the `GlobalFactory` ownership by injecting a `RefPtr<GlobalFactory>` directly inside all wrapper objects deriving from `TrackedObject`. This releases the `GlobalFactory::alive_objects_` collection from its duty of maintaining an object count, and makes
reference counting the sole mechanism for initializing and shutdown the library. This also reduces the number of locks needed, as tracker objects (which therefore own a ref) can create other tracker objects without the need to check if the library is initialized, since it obviously is.
This is a follow-up to #197.
> Add RefPtr<GlobalFactory> to TrackedObject

- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
Somehow this worked as intended in m71 even without setting the flag, but it is not the case on latest master.
> Set `negotiated` flag correctly

- libs/Microsoft.MixedReality.WebRTC/DataChannel.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/DataChannelInterop.cs
avoids per-message byte[] array allocation, can be used in unsafe contexts.
> DataChannel: SendMessage(IntPtr,ulong) / MessageReceivedUnsafe callback

- README.undock.md
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
- Change libwebrtc path for Win32 project
- Add WindowsApp.lib to Win32 dependencies (necessary for new audio module)
- Update docs
> Allow Win32 and UWP builds side by side

- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Was deleted by mistake by 3e8ca31a04fbf0728b0bc7fae5223158baad0464.
> Restore extra params override in remote description

- examples/TestAppUwp/MainPage.xaml.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/VideoChatDemo/VideoChatDemo.prefab
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/Signaler.cs
- Remove any mention of Signaler in PeerConnection.
- Remove the node-dss specific message type from the Signaler abstract
base class, and move it to the specific NodeDssSignaler
implementation.
Note that currently Signaler encapsulates messages into a Message type,
which is then re-encapsulated into a different NodeDssMessage type by
the NodeDssSignaler. This looks redundant, but there are 2 reasons for
this:
- NodeDssSignaler needs a specific message type that serializes to JSON
with specific field names, to be compatible with the node-dss
protocol.
- The Signaler.Message type will eventually move into the C# library API
and be transparent to the user (#188).
Bug: #172
> Remove Signaler use from PeerConnection

- libs/Microsoft.MixedReality.WebRTC/Interop/DataChannelInterop.cs
ref structs are not implicitly passed by ref, at least not in IL2CPP.
> Fix DataChannelCreateObjectCallback signature

- libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/data_channel_tests.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/DataChannelInterop.cs
Ensure that reverse P/Invoke struct containing a string type is passed
by value and not by reference, to ensure proper marshaling.
This essentially reverts f1b3328e and 43272b8d5, and actually fix the
C++ callsites instead to pass by value again.
Validated on:
- Desktop x64 Debug & Release (native tests)
- UWP x64 Debug & Release (TestAppUWP)
- UWP ARM Debug & Release (Unity deploy to HL2 via IL2CPP)
Note that this will go away with the multi-track refactor (#152).
> Fix marshaling of data channel create config

- libs/Microsoft.MixedReality.WebRTC/IAudioTrack.cs
- libs/Microsoft.MixedReality.WebRTC/IVideoTrack.cs
- libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
- libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
- libs/Microsoft.MixedReality.WebRTC/RemoteAudioTrack.cs
- libs/Microsoft.MixedReality.WebRTC/RemoteVideoTrack.cs
Add some interfaces for audio and video tracks to allow manipulating
them generically, irrelevant of whether the track is local or remote.
This allows applications to register some frame callback and check the
enabled status of the track, which are common properties to all audio
and video tracks.
> Add IAudioTrack and IVideoTrack interfaces

- libs/Microsoft.MixedReality.WebRTC.Native/include/transceiver_interop.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/transceiver_interop.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/transceiver.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/media/transceiver.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/TransceiverInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Microsoft.MixedReality.WebRTC.csproj
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- libs/Microsoft.MixedReality.WebRTC/Transceiver.cs
Fix duplicate media line index occurring when both peers create a transceiver before an offer by exposing the real `mid` attribute of the JSEP session as it appears in the SDP message. This allows better insight into the actual state of the transceivers.
Practically this changes a few things:
- The `Transceiver.MlineIndex` property may be invalid (negative) when the transceiver is not yet associated with a media line. Once an offer associates it, a new `Transceiver.Associated` event is raised and the property takes the actual value of the `mid` SDP attribute.
- Corollary of the above, the media line index of the transceivers of the `PeerConnection.Transceivers` array do not form anymore a contiguous sequence of indices [0..N], since data channels also consume a media line, and …
> Fix duplicate media line index by exposing real mid

- examples/TestReceiveAV/Program.cs
Restore the original author's license header and remove the Microsoft
license header to reflect the fact that this file was contributed by a
third-party author and not written by a Microsoft employee, in
accordance with the official Microsoft copyright headers policy for
open-source projects.
> Fix license of TestReceiveAV/Program.cs

- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/utils.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/utils.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/src/uwp/Microsoft.MixedReality.WebRTC.Native.UWP.vcxproj.filters
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/src/win32/Microsoft.MixedReality.WebRTC.Native.Win32.vcxproj.filters
Merge PeerConnectionImpl and the PeerConnection interface into a single
concrete class, as the `mrwebrtc` library is now exposing only a C-style
API and does not need to hide C++ inline methods and template types
anymore. This simplifies implementation by removing all the abstraction
boilerplate.
> Remote PeerConnection interface from internal impl

- tests/Microsoft.MixedReality.WebRTC.Tests/TransceiverTests.cs
Fix C# transceiver test for SetDirection to match the actual cases the renegotiation needed event is raised, as described in the standard.
> Fix C# transceiver test

- libs/mrwebrtc/src/data_channel.cpp
- libs/mrwebrtc/src/peer_connection.cpp
Raise the data channel added event earlier and more consistently for
out-of-band data channels when the data channel is created and added to
the peer connnection, instead of waiting for its state to change to
open, as the latter happens asynchronously much latter. This simplifies
interop wrapper creation, and makes the codepath consistent with in-band
data channels which already raise that event inline during the call to
AddDataChannel().
> Earlier and more consistent DataChannelAdded event

- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/AudioSender.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/VideoSender.cs
Add a warning indicating that the per-track preferred media codec is not
yet implemented, and the track value will override the peer connection's
global value.
This shall eventually be fixed, and per-track support added, but the change
is not trivial, so adding at least a warning until then and fixing parity of
audio and video tracks.
> Add warning for missing per-track preferred codec

- cgmanifest.json
- tools/ci/release-core-nosign.yaml
- tools/ci/templates/jobs-libwebrtc-uwp.yaml
- tools/ci/templates/jobs-libwebrtc-win32.yaml
- tools/ci/templates/steps-install-python2x.yaml
- Fix the release pipeline building the Google's implementation library `libwebrtc` to build on on-prem agents.
- Add a Component Governance task before the build to detect components in use by the project.
- Ensure the security report for those components is clean by deleting unused code before detection and building to make sure potentially vulnerable code present in Google's build tools _etc._ is not used in the build and not shipped.
- Update `cgmanifest.json` with the correct commits for all used git repositories.
> Fix release pipeline with component detection

- tools/build/libwebrtc/mrwebrtc.ps1
- tools/ci/mapVariables.ps1
Before Component Governance scanning and `libwebrtc` building occur, delete components checked out on disk by Google's tools but unused, and which trigger some security vulnerability alerts. This makes sure those vulnerabilities cannot possibly make it into MixedReality-WebRTC, and makes the security checks pass.
> Delete unused components before CG scan

- examples/TestAppUwp/Model/SessionModel.cs
- examples/TestAppUwp/NodeDssSignaler.cs
- examples/TestNetCoreConsole/NamedPipeSignaler.cs
- examples/TestNetCoreConsole/Program.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Examples/StandaloneDemo/LocalOnlySignaler.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Editor/EditorTests.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/PeerConnection.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/Signaler.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- libs/Microsoft.MixedReality.WebRTC/Tracing/MainEventSource.cs
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/mrwebrtc/src/peer_connection.cpp
- libs/mrwebrtc/src/peer_connection.h
- libs/mrwebrtc/src/sdp_utils.cpp
- libs/mrwebrtc/src/sdp_utils.h
- libs/mrwebrtc/test/data_channel_tests.cpp
- libs/mrwebrtc/test/peer_connection_test_helpers.h
- libs/mrwebrtc/test/peer_connection_tests.cpp
- tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTestBase.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/PeerConnectionTests.cs
Add an enum type for the SDP message type, and a C# SdpMessage class, to
pass the SDP messages around with additional type safety and without the
risks associated with string comparison (locale, misspelling, ...).
Bug: #188
> Use enum and message type for SDP messages

- examples/TestAppUwp/MainPage.xaml.cs
- examples/TestAppUwp/SettingsPage.xaml.cs
Save and restore preferred codecs in TestAppUWP via app settings, to avoid having to change settings on each run.
> [TestAppUWP] Save/restore preferred codecs via app settings

- tools/build/libwebrtc/mrwebrtc.ps1
Dependency of the desktop_capture module, deleting it prevents building win32.
> Maintain tools/generate-stubs

- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime.asmdef
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/PeerConnectionTests.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/VideoSenderTests.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/VideoSenderTests.cs.meta
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity.Tests.Runtime/VideoSourceTests.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/AudioSender.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/MediaSender.cs
- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/VideoSender.cs
Avoid creating a local audio or video track (webcam/microphone) if the
component is not active. Instead leave the Track property as NULL.
> Only create local tracks if component is active

- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Media/SceneVideoSender.cs
Prevent the SceneVideoSender component from being enabled if
asynchronous GPU readback is not supported by the target device. This is
common on Android targets using the OpenGL graphics backend, which has
no support for this feature (and won't ever get it according to Unity).
More recent Android devices can use Vulkan instead, which supports
asynchronous GPU readback.
> Disable SceneVideoSender w/o async GPU readback

- libs/Microsoft.MixedReality.WebRTC.Unity/Assets/Microsoft.MixedReality.WebRTC.Unity/Scripts/Signaling/NodeDssSignaler.cs
Work around the built-in logcat limit on Android (about 1000 characters)
by splitting some hand-picked debug messages known to generally be
longer than that. This prevent those messages from being truncated in
logcat.
> Split long log messages on Android for logcat

- tools/build/android/webrtc-native/build.gradle
The default debug configuration on Android leaves debug symbols for
mrwebrtc, but strips them for private symbols, especially those in
libwebrtc. This makes debugging through that code difficult.
This change adds a fulldebug build variant which removes that stripping,
at the expense of producing a much larger Android archive (x5).
> Add fulldebug config to Android project

- examples/TestAppUwp/MainPage.xaml.cs
Prevent the local peer ID from being an empty string when launching a
second instance while the saved settings contain an empty string for the
remote peer, which gets swapped in that second instance with the local
peer after the empty string override has been applied. Instead apply the
fallback after the 2-instance helper possibly swapped the values.
> Fix crash in TestAppUWP on invalid local peer ID

- libs/Microsoft.MixedReality.WebRTC/Microsoft.MixedReality.WebRTC.csproj
Fix the path of the post-build step of the C# library which copies the
C# library DLL into the Unity library Plugins folder.
> Fix C# library copy to Unity plugin after build

- libs/Microsoft.MixedReality.WebRTC/Exceptions.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/mrwebrtc/include/result.h
Add some error code to signal the user a buffer is too small to perform
the current operation. The buffer is generally allocated by the caller,
which gives them an opportunity to retry with a larger buffer.
> Add E_BUFFER_TOO_SMALL error code

- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-unity-package.yaml
- tools/ci/writeNpmrc.ps1
Update the Unity release pipeline to publish to any chosen NPM register
external to the current Azure DevOps account where the release pipeline
is running.
> Publish Unity packages to external NPM register

- tools/ci/ci-cpp.yaml
- tools/ci/computePdbPackageVars.ps1
- tools/ci/copyPdbsForBuilding.ps1
- tools/ci/copyPdbsForPackaging.ps1
- tools/ci/generateCppPackagesConfig.ps1
- tools/ci/mapVariables.ps1
- tools/ci/modifyCppProject.ps1
- tools/ci/templates/jobs-cpp.yaml
Before the build starts, delete unused files checked out by the Google build
scripts but not used in the build, and optionally run the Component Governance
detection task to monitor use of third-party software for compliance.
> Add optional CG task to mrwebrtc build template

- examples/TestAppUwp/MediaPlayerPage.xaml.cs
- examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
- examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
- examples/TestNetCoreConsole/Program.cs
- libs/Microsoft.MixedReality.WebRTC/AudioTrackSource.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/AudioTrackSourceInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/LocalAudioTrackInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
- libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
- libs/mrwebrtc/include/audio_track_source_interop.h
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/include/local_audio_track_interop.h
- libs/mrwebrtc/src/interop/audio_track_source_interop.cpp
- libs/mrwebrtc/src/interop/global_factory.cpp
- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/mrwebrtc/src/interop/local_audio_track_interop.cpp
- libs/mrwebrtc/src/media/audio_track_source.cpp
- libs/mrwebrtc/src/media/audio_track_source.h
- libs/mrwebrtc/src/tracked_object.h
- libs/mrwebrtc/test/audio_track_source_tests.cpp
- libs/mrwebrtc/test/audio_track_tests.cpp
- tests/Microsoft.MixedReality.WebRTC.Tests/AudioTrackSourceTests.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/LocalAudioTrackTests.cs
- tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
- tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
- tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
- tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
- tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Split the audio track source from the audio track, to allow sharing
across peer connections.
This change splits the former local audio track into 2 separate
components:
- The audio track source, which generates the raw audio frames,
generally from a local audio capture device (microphone) but not
necessarily. At this time only device-based sources are supported
though. The audio track source is not associated with any peer
connection in particular, and can be shared amongst any number of
local audio tracks, from the same peer connection or not.
- The local audio track, which is associated with a particular peer
connection, and which is a slim bridge between an audio track source
and the audio transceiver of the peer connection.
This change adds support to the native and C# libraries only.
> Add split audio track source

- libs/unity/library/Runtime/Scripts/Media/MediaPlayer.cs
- libs/unity/library/Runtime/Shaders/ARGBFeedShader.shader
- libs/unity/library/Runtime/Shaders/ARGBFeedShaderUnlit.shader
- libs/unity/library/Runtime/Shaders/YUVFeedShader.shader
- libs/unity/library/Runtime/Shaders/YUVFeedShaderUnlit.shader
Fix video being rendered vertically flipped by the MediaPlayer component
when using the YUVFeedShader(Unlit) or ARGBFeedShader(Unlit) on
platforms using the OpenGL graphics API.
The Unity Texture2D.LoadRawTextureData() method used by the MediaPlayer
component always expects bottom-up image data, even when using Direct3D,
but the WebRTC video frames are always top-down. Instead of using a
costly CPU transform, simply upload the video frames inverted into the
YUV planar textures or the ARGB texture, and use the shader to flip the
texture back before rendering.
Bug: #388
> Fix vertical flip of video on OpenGL platforms

- examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
- examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
- examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
- examples/TestNetCoreConsole/Program.cs
- libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
- libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/LocalAudioTrackTests.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
The process of creating the track from the source consists solely in creating the track object, and is therefore lightweight and does not mandate an asynchronous call. Make it synchronous for simplicity.
> Make Track.CreateFromSource synchronous

- tools/ci/release-cpp.yaml
- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-unity-package.yaml
Make the Unity UPM release pipeline sign the Windows DLLs before packaging.
> Add Windows DLL signing to Unity UPM release pipeline

- docs/index.md
Update the landing page of the documentation website to display the
branch and version of the documentation, to prevent confusion about API
version.
> Update docs front page with branch/version

- libs/mrwebrtc/test/object_tests.cpp
API calls require the use of uint64_t by convention to avoid the
architecture-dependent size of size_t. Using size_t generates a cast
error on x86 architectures.
> Fix invalid use of size_t instead of uint64_t

- examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
Fix a regression in TestAppUWP where the selected video profile was not
assigned anymore when opening the webcam, which prevented using video
profiles.
> [TestAppUWP] Assign selected video profile

- examples/TestAppUwp/ViewModel/AudioCaptureViewModel.cs
- examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
- examples/TestNetCoreConsole/Program.cs
- libs/Microsoft.MixedReality.WebRTC/AudioTrackSource.cs
- libs/Microsoft.MixedReality.WebRTC/DeviceAudioTrackSource.cs
- libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/AudioTrackSourceInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/DeviceAudioTrackSourceInterop.cs
- libs/mrwebrtc/include/audio_track_source_interop.h
- libs/mrwebrtc/include/device_audio_track_source_interop.h
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/audio_track_source_interop.cpp
- libs/mrwebrtc/src/interop/device_audio_track_source_interop.cpp
- libs/mrwebrtc/src/media/audio_track_source.cpp
- libs/mrwebrtc/src/media/audio_track_source.h
- libs/mrwebrtc/src/media/device_audio_track_source.cpp
- libs/mrwebrtc/src/media/device_audio_track_source.h
- libs/mrwebrtc/src/tracked_object.h
- libs/mrwebrtc/src/utils.cpp
- libs/mrwebrtc/test/audio_track_tests.cpp
- libs/mrwebrtc/test/device_audio_track_source_tests.cpp
- tests/Microsoft.MixedReality.WebRTC.Tests/AudioTrackSourceTests.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/LocalAudioTrackTests.cs
- tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
- tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
- tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
- tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
- tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Split the audio track source base class from the actual device-based
implementation, and make the former abstract. This allow extensibility
in the future to add e.g. an external audio track source, and makes the
API consistent with video track sources.
> Split audio device source and base audio source

- docs/docfx.json
- docs/template/mr-webrtc/layout/_master.tmpl
- docs/template/mr-webrtc/partials/logo.tmpl.partial
- docs/template/mr-webrtc/styles/main.css
- Fix missing favicon
- Add project name next to icon in title bar
- Remove empty breadcrumb bar on index page
- Change search bar and branch selector designs
> Miscellaneous docs appearance fixes

- libs/mrwebrtc/src/video_frame_observer.cpp
- libs/mrwebrtc/src/video_frame_observer.h
Properly handle ARGB buffer recycling in VideoFrameObserver when the
buffer rotates, which keeps the overall storage size but requires an
update of the width, height, and most importantly stride.
> Recycle ARGB buffer when frame rotates

- libs/unity/library/Runtime/Scripts/Media/MicrophoneSource.cs
- libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
Catch exceptions when failing to create a device track source in WebcamSource
and MicrophoneSource components, and log the exception with its callstack along
with an error message with the component name.
This is a clean-up loosely related to #335, though the code triggering that
issue has been changed so the issue does not occur anymore.
> Log when exception occur in device sources

- libs/Microsoft.MixedReality.WebRTC/LocalAudioTrack.cs
- libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
- libs/Microsoft.MixedReality.WebRTC/MediaTrack.cs
- libs/unity/library/Runtime/Scripts/Media/AudioTrackSource.cs
- libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
- libs/unity/library/Runtime/Scripts/Media/VideoRenderer.cs
- libs/unity/library/Runtime/Scripts/Media/VideoTrackSource.cs
The fix is in MediaLine.OnAfterDeserialize. The rest is small refactorings/simplifications.
This fixes #426. The behavior is still a bit weird - we are removing the source from the MediaLine when it is disabled, but have no way to re-add it when it is re-enabled.
> Always add MediaLines to track source

- .gitmodules
- libs/Microsoft.MixedReality.WebRTC/Interop/LoggingInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Logging.cs
- libs/mrwebrtc/include/logging_interop.h
- libs/mrwebrtc/src/interop/logging_interop.cpp
- libs/mrwebrtc/src/pch.h
- libs/mrwebrtc/test/data_channel_tests.cpp
- libs/mrwebrtc/test/logging_tests.cpp
- tests/Microsoft.MixedReality.WebRTC.Tests/LoggingTests.cs
- tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj
- tools/build/mrwebrtc/uwp/mrwebrtc-uwp.vcxproj.filters
- tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj
- tools/build/mrwebrtc/win32/mrwebrtc-win32.vcxproj.filters
- tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Allow the user to register a callback invoked each time a message is
logged by the internal WebRTC implementation. This allows better error
reporting and easier debugging without the need to connect a debugger or
even have debug symbols available (PDBs).
> Expose WebRTC logging via user callback

- README.undock.md
- tools/build/build.py
Add a Python build.py script for Windows builds which automatically
clone the Google repository and eventually applies the UWP patches if
needed, then build the given variant. This greatly simplifies building
for users.
> Add Python build script for Windows builds

- libs/unity/library/Runtime/Scripts/Media/AudioTrackSource.cs
- libs/unity/library/Runtime/Scripts/Media/CustomVideoSource.cs
- libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
- libs/unity/library/Runtime/Scripts/Media/MediaTrackSource.cs
- libs/unity/library/Runtime/Scripts/Media/MicrophoneSource.cs
- libs/unity/library/Runtime/Scripts/Media/SceneVideoSource.cs
- libs/unity/library/Runtime/Scripts/Media/VideoTrackSource.cs
- libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
- libs/unity/library/Tests/Runtime/MediaLineTests.cs
- libs/unity/library/Tests/Runtime/VideoSenderTests.cs
- libs/unity/library/Tests/Runtime/VideoSourceTests.cs
MediaLines now create a sender track when a source is attached *and* live,
and destroy it if any of these is false.
Note that we could delay track creation to when a connection is established,
but this is simpler to do, and local tracks should be lightweight so creating
them eagerly won't make much of a difference.
> Handle source enable/disable correctly

- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-mrwebrtc-release-build.yaml
- Ensure clean builds by default for release builds (not incremental)
- Restore --cpp17 flag to fix inconsistency between libwebrtc and mrwebrtc
> Fix and ensure clean builds for release

- libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
- libs/unity/library/Runtime/Scripts/Media/MediaReceiver.cs
- libs/unity/library/Runtime/Scripts/Media/MediaTrackSource.cs
- libs/unity/library/Runtime/Scripts/PeerConnection.cs
- libs/unity/library/Tests/Runtime/MediaLineTests.cs
- libs/unity/library/Tests/Runtime/PeerConnectionTests.cs
- libs/unity/library/Tests/Runtime/VideoSenderTests.cs
- libs/unity/library/Tests/Runtime/VideoSourceTests.cs
Connecting in OnAfterDeserialize wasn't correct:
- source/receiver might not be deserialized yet when OnAfterDeserialize is
called
- OnAfterDeserialize is called multiple times for the same object, which
triggered asserts
- OnAfterDeserialize is not called on the update thread (which isn't great
for calling an external callback)
Fixes #446.
> Connect MediaLines only on PeerConnection awake

- tools/ci/templates/jobs-libwebrtc-android.yaml
Ensure the correct mrwebrtc.aar artifact is staged for packing by
pointing the staging task to the merged archive (containing both
MixedReality-WebRTC and libwebrtc Java classes) instead of the unmerged
one (missing the latter).
> Fix Unity release Android artifact staging path

- libs/Microsoft.MixedReality.WebRTC/IVideoSource.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/LocalVideoTrackInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/RemoteVideoTrackInterop.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/VideoTrackSourceInterop.cs
- libs/Microsoft.MixedReality.WebRTC/LocalVideoTrack.cs
- libs/Microsoft.MixedReality.WebRTC/RemoteVideoTrack.cs
- libs/Microsoft.MixedReality.WebRTC/VideoTrackSource.cs
- libs/mrwebrtc/src/media/video_track_source.cpp
- libs/mrwebrtc/src/media/video_track_source.h
- libs/mrwebrtc/src/video_frame_observer.h
- tests/Microsoft.MixedReality.WebRTC.Tests/LocalVideoTrackTests.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/RemoteTrackTest.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/VideoEnum.cs
- tests/Microsoft.MixedReality.WebRTC.Tests/VideoTrackSourceTests.cs
Fixes #151, a deadlock caused by subscription and frame-ready event trying to acquire the callback lock and the WebRTC worker thread at the same time, wrong behavior when using both I420A and ARGB32 callbacks, and a non-compiling test.
> Fix issues with frame ready callbacks

- examples/TestAppUwp/AddVideoTrackPage.xaml
- examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
- libs/Microsoft.MixedReality.WebRTC/DeviceVideoTrackSource.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/DeviceVideoTrackSourceInterop.cs
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/mrwebrtc/src/media/device_video_track_source.cpp
- libs/mrwebrtc/src/media/device_video_track_source.h
Add the ability to enumerate the video profiles of a video capture device, and
to retrieve the video capture formats for any profile. This fixes an issue
where only video capture formats for the default profile were returned, by
allowing the user to specifically enumerate profiles and their associated
capture formats.
Bug: #159
> Enumerate video profiles and filter capture formats

- libs/mrwebrtc/src/peer_connection.cpp
- libs/unity/library/Tests/Runtime/MediaLineTests.cs
This avoids crashing callbacks/observers if the pointer is reset while they are
running. Any callback (including the ones that might add objects) will complete
when peer_->Close() is called and its results will be cleaned up with all the
rest.
Note that this assumes that there are no multi-threaded calls to our API - but
this should be the case already.
Fixes #463.
> Do not reset impl when closing PeerConnection

- libs/unity/library/Runtime/Scripts/PeerConnection.cs
The return type changed with 4b7e8854
> [Unity] Fix wrong return type in format enum

- CHANGELOG.md
- README.md
- docs/index.md
Update the docs title page to differentiate between "2.0" and "latest" docs,
even though they are the same as of today.
Also update the README.md and CHANGELOG.md to add references to 2.0; those
changes need to be merged to `master` too after that.
> Update docs title and README/CHANGELOG for 2.0

- tools/nuget/Desktop/Microsoft.MixedReality.WebRTC.nuspec
- tools/nuget/Desktop/mrwebrtc.nuspec
- tools/nuget/UWP/Microsoft.MixedReality.WebRTC.UWP.nuspec
- tools/nuget/UWP/mrwebrtc_uwp.nuspec
Fix the URL of the NuGet packages icon, which was pointing to the
generic GitHub page for the file (HMTL) instead of the raw file content
(PNG). This should make the icon appear on nuget.org and in the various
NuGet clients (e.g. Visual Studio NuGet package manager).
> Fix NuGet packages icon

- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/Library.cs
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/global_factory.cpp
- libs/mrwebrtc/src/interop/global_factory.h
- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/mrwebrtc/src/pch.h
Switch audio implementation on Windows Desktop to the new Core Audio
based audio device module (ADM2), which avoids a crash in ADM1 when one
device is not supported by that module (even if unused), like Azure
Kinect DK.
Add a new function |mrsLibraryUseAudioDeviceModule2()| to enable users
to switch back to ADM1 in case there would be issues with ADM2, as
support and maturity of ADM2 are unclear, and the module is not always
well tested, though is the recommended way from Google going forward.
Bug: #124
> Switch to ADM2 on Windows Desktop

- libs/mrwebrtc/src/interop/logging_interop.cpp
- tools/ci/ci-cpp.yaml
- tools/ci/templates/jobs-cpp.yaml
Update the CI pipeline to build mrwebrtc on Windows from sources, without the
use of the deprecated Core NuGet packages.
Also fix some minor issues with some method signature on x86 and some Component
Governance alert.
> Update mrwebrtc CI to build without NuGet Core

- tools/build/build.ps1
Add the Visual Studio "Professional" variant in addition of Community
and Enterprise when looking for the MSBuild.exe path.
Bug: #515
> Add missing VS2019 variant to build.ps1

- examples/TestAppUwp/App.xaml
- examples/TestAppUwp/Model/SessionModel.cs
- examples/TestAppUwp/SettingsPage.xaml
- examples/TestAppUwp/ViewModel/Converters.cs
- examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/interop_api.cpp
The configuration can be tweaked to get improved video quality. This is a
mitigation for #153.
Important: using a profile different from (Constrained) Baseline requires
specifying the correct `profile-level-id` parameter in the corresponding SDP
codec entry for other peers to correctly accept/reject the codec. This change
does not change SDP offer from the default (unspecified, equivalent to
Baseline). If using a higher profile, you must ensure that all peers support
encoding/decoding at that profile, or the behavior will be undefined.
> Expose H.264 encoder configuration 

- libs/mrwebrtc/src/interop/global_factory.cpp
> Use custom AudioMixer on UWP

- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/global_factory.cpp
- libs/mrwebrtc/src/interop/global_factory.h
- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/mrwebrtc/src/media/device_video_track_source.cpp
UnityUtility has been changed into AndroidCameraInterop, so use that.
> Fix issues with Android build

- libs/Microsoft.MixedReality.WebRTC/VideoTrackSource.cs
If the GCHandle corresponding to the source, and used by the FrameReady
callbacks, is invalidated while the callbacks are still running, it can cause a
crash when used in VideoTrackSourceInterop.I420AFrameCallbackFunction.
Now we release the GCHandle only after the native source has been disposed,
because at that point callbacks are not being called anymore.
The crash only seems to happen regularly on Android.
> Fix potential crash on disposing a VideoTrackSource

- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/Library.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/interop/global_factory.cpp
- libs/mrwebrtc/src/interop/global_factory.h
- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/unity/library/Runtime/Scripts/AsyncInitHelper.cs
- libs/unity/library/Runtime/Scripts/AsyncInitHelper.cs.meta
- libs/unity/library/Runtime/Scripts/Media/MicrophoneSource.cs
- libs/unity/library/Runtime/Scripts/Media/UwpUtils.cs
- libs/unity/library/Runtime/Scripts/Media/UwpUtils.cs.meta
- libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
- libs/unity/library/Runtime/Scripts/PeerConnection.cs
- libs/unity/library/Tests/Runtime/PeerConnectionTests.cs
- libs/unity/library/Tests/Runtime/VideoSourceTests.cs
If a component containing a WebRTC resource with async initialization is
disabled before the resource has finished initializing, now we block the
OnDisable call and properly dispose the resource.
Refactored permission requests on Android to use async methods, so they
integrate better with the rest of the code.
Fixes #464.
> Handle OnDisable while resource is initializing

- tools/build/libwebrtc/build.sh
- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-libwebrtc-android.yaml
- tools/ci/templates/jobs-mrwebrtc-release-build.yaml
Delete unused files after checkout and before building, to avoid compliance alerts in unused code.
> Fix component governance alerts in Unity build

- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-libwebrtc-android.yaml
Delete unused code before scanning for vulnerabilities to avoid false positives.
> Fix invalid security alerts in CG report

- tools/build/android/webrtc-native/build.gradle
- tools/build/android/webrtc-native/merge-archives.sh
This covers #571 and successfully builds for Android under Windows with `libwebrtc` being built under WSL2 while at the same time leaving native Linux builds unaffected.
This is achieved by updating `build.gradle` with a robust (escaped) `$projectDir` path and then conditional on WSL2 kernels applying some regular expression for transforming it into a `/mnt/c/...` path format that is WSL2 compliant.
@fibann annd @djee-ms If you have some preferences regarding the print outs or other comments, please let me know and I am happy to update them accordingly. It would also be great if we can double check that native Linux is actually unaffected since I haven't tested this yet.
> Fix merge-archives.sh Android build under Windows WSL2

- tools/ci/ci-android.yaml
- tools/ci/templates/jobs-libwebrtc-android.yaml
Add some very basic Android CI building `mrwebrtc.aar` in Debug. This takes an awful amount of time (~1 hour) so batching changes (run at most 1 agent at once, with all commits since last run, instead of 1 run per commit). Hopefully this will catch at least some building regressions more quickly before they hit users.
> Add basic Android CI

- tools/ci/templates/jobs-unity-package.yaml
Remove from the Unity UPM package the .meta files related to PDB files
if those PDB files are not packaged, to avoid warnings in Unity.
Bug: #592
> Remove .meta files if PDB not packaged

- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-mrwebrtc-release-pack.yaml
- tools/ci/templates/jobs-unity-package.yaml
Allow the release pipelines for Windows NuGet and Unity UPM to publish internally some artifact with all PDBs of the release build, with the intention of later being able to make them public if possible (TBD).
> Publish PDBs separately in release pipelines

- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/mrwebrtc/include/result.h
- libs/mrwebrtc/src/interop/remote_audio_track_interop.cpp
- libs/mrwebrtc/src/media/audio_track_read_buffer.cpp
- libs/mrwebrtc/src/media/audio_track_read_buffer.h
- libs/mrwebrtc/test/audio_track_read_buffer_tests.cpp
- tools/build/mrwebrtc/win32/tests/mrwebrtc-win32-tests.vcxproj
Handle failures to resample audio to the given frequency with an
explicit error code instead of an assertion. Log a warning that the
audio frame is dropped, and return an error code from the audio track
read buffer's read call.
> Handle audio resampling failure with error code

- examples/TestAppUwp/Model/SessionModel.cs
- libs/Microsoft.MixedReality.WebRTC/DataChannel.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Obsolete the `PeerConnection.Initialized` property of the C# library, and
add some warning in the documentation about its undefined value while
the `InitializeAsync()` call is underway.
Users are encouraged to not use this property anymore, and instead
directly rely on the result of the async call, and more precisely when
its task is completed.
Bug: #651
> Obsolete PeerConnection.Initialized

- libs/Microsoft.MixedReality.WebRTC/DataChannel.cs
- libs/Microsoft.MixedReality.WebRTC/Interop/DataChannelInterop.cs
- libs/mrwebrtc/include/data_channel_interop.h
- libs/mrwebrtc/src/data_channel.cpp
- libs/mrwebrtc/src/data_channel.h
- libs/mrwebrtc/src/interop/data_channel_interop.cpp
Finally got around to this update. I've updated the solution to not be a breaking change. Added new method for sending text messages over the data channel.
Added a new event which is fired when non-binary data is received.
This will still be a change in the inner workings of the mr-webrtc dll. I've opened up an issue to discuss what can be done about it below!
> Add text message support for data channel send and receive callbacks.

- tools/ci/templates/jobs-mrwebrtc-release-build.yaml
Prevent out-of-disk-space error by compressing the libwebrtc output folders
after building `webrtc.lib`. Those folders contain mainly `.obj` and `.pdb`
files, which are highly compressible (1:2 to 1:4 ratios) and are very large in
the first place, making some agents run out of disk space during build.
Also fix release CI to build only the UWP wrappers (`.lib`) and not the full
WinRT projection (`.dll`), which is not used and consumes CPU time, RAM, and
disk space, for nothing.
> Compress webrtc.lib out folder in release CI

- libs/mrwebrtc/include/local_audio_track_interop.h
- libs/mrwebrtc/include/local_video_track_interop.h
- libs/unity/library/Runtime/Scripts/Attributes/SdpTokenAttribute.cs
- libs/unity/library/Runtime/Scripts/Signaling/NodeDssSignaler.cs
If no local peer ID is set, NodeDssSignaler derives it from the device ID. Apparently, it's quite common for them on Android to contain spaces, which aren't allowed in SDP tokens. If we fix this, we might as well go all the way.
> NodeDssSignaler: Ensure that the local peer ID is a valid SDP token

- examples/TestNetCoreConsole/NamedPipeSignaler.cs
- examples/TestNetCoreConsole/Program.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
PR for issue described in https://github.com/microsoft/MixedReality-WebRTC/issues/722
The data channel memory was freed twice, once by the caller and then once again by an event registration, from what I can tell the event registration is there to handle when a remote peer removes a data channel.
Also added some code so the NamedPipeSignaler demo doesn't crash as much.
> fix: do not attempt to release data channel memory twice
