microsoft/MixedReality-WebRTC

- docs/manual/building.md
For me it was confusing the first time I tried the example scene so I just fixed the wrong scene name :)
> The name of the demo scene was wrong so I fixed it.

- examples/TestAppUwp/Video/VideoBridge.cs
This greatly reduce GC occurrences
> Reuse scratch buffer for deferred frame

- examples/TestAppUwp/MainPage.xaml.cs
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/pch.h
- libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Add usage example in TestAppUWP.
Mitigates #107.
>  Expose PeerConnectionInterface::SetBitrate 

- examples/TestAppUwp/MainPage.xaml.cs
- libs/Microsoft.MixedReality.WebRTC.Native/include/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/PeerConnectionInterop.cs
- libs/Microsoft.MixedReality.WebRTC/PeerConnection.cs
Made a simplified wrapper around the WebRTC stats API that contains only a few stats parameters considered of common use.
> Add simple statistics gathering

- libs/Microsoft.MixedReality.WebRTC.Native/test/audio_track_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/data_channel_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/external_video_track_source_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/memory_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/peer_connection_test_helpers.h
- libs/Microsoft.MixedReality.WebRTC.Native/test/peer_connection_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/sdp_utils_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/video_frame_observer_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/video_track_tests.cpp
Fix CI after #190 breaks. Related to #123.
> Fix/disable tests that use private API

- libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/global_factory.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/interop_api.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/Microsoft.MixedReality.WebRTC.Native.Tests.vcxproj
- libs/Microsoft.MixedReality.WebRTC.Native/test/library_tests.cpp
- libs/Microsoft.MixedReality.WebRTC/Interop/InteropUtils.cs
- libs/Microsoft.MixedReality.WebRTC/Library.cs
Expose:
- Set/get shutdown options
- Report live objects
- Force shutdown
> Expose some library-wide functionalities

- libs/Microsoft.MixedReality.WebRTC.Native/include/interop_api.h
- libs/Microsoft.MixedReality.WebRTC.Native/include/peer_connection_interop.h
- libs/Microsoft.MixedReality.WebRTC.Native/src/interop/peer_connection_interop.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/src/peer_connection.h
- libs/Microsoft.MixedReality.WebRTC.Native/test/audio_track_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/external_video_track_source_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/transceiver_tests.cpp
- libs/Microsoft.MixedReality.WebRTC.Native/test/video_track_tests.cpp
This simplifies both the implementation and any wrapper layer above it.
> Merge A/V transceivers creation + fix refcount bug

- docs/manual/cs/helloworld-cs-core3.md
- docs/manual/cs/helloworld-cs-uwp.md
- docs/manual/download.md
- docs/manual/installation.md
Add temporary warnings where due until some serious issues are fixed, to prevent users from getting stuck on them.
> Add warnings to docs where due

- examples/TestAppUwp/AddVideoTrackPage.xaml
- examples/TestAppUwp/ViewModel/MediaPlayerViewModel.cs
- examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
Fix the display of the video capture format encoding in the list of capture formats.
> Show video capture encoding in format in list

- libs/mrwebrtc/src/peer_connection.cpp
Change the implementation of ExtractMlineIndexFromRtpTransceiver() to
use the actual mline index retrieved from the internal implementation
instead of trying to deduce it from the mid value, because other
implementations than Google's may not use the mline index as the mid
value and this breaks interoperability. This is a workaround for the
fact the mline index is not exposed in the RtpTransceiverInterface.
Bug: #295
> Retrieve actual mline index instead of mid

- tools/build/android/debugging.md
Add some more docs about Android debugging, especially caveats of source
remapping.
> More Android debugging docs

- libs/mrwebrtc/src/toggle_audio_mixer.cpp
Previous code asserted if OutputSource was called twice with different values before AddSource.
> Add/remove Source only if not null

- docs/manual/cs/helloworld-cs-connection-core3.md
- docs/manual/cs/helloworld-cs-core3.md
- docs/manual/cs/helloworld-cs-mediatracks-core3.md
- docs/manual/cs/helloworld-cs-peerconnection-core3.md
- docs/manual/cs/helloworld-cs-setup-core3.md
- docs/manual/cs/helloworld-cs-signaling-core3.md
- examples/TestNetCoreConsole/Program.cs
Update the tutorial for the .NET Core 3.0 project to reflect latest
changes already present in the repository.
Bug: #244
> Update the .NET Core 3.0 tutorial

- docs/manual/glossary.md
- docs/manual/toc.md
- docs/template/mr-webrtc/styles/main.css
Add a new documentation page containing a glossary of common WebRTC
concepts explained.
> Add a glossary to the documentation

- libs/mrwebrtc/include/data_channel_interop.h
- libs/mrwebrtc/include/interop_api.h
- libs/mrwebrtc/src/data_channel.cpp
- libs/mrwebrtc/src/data_channel.h
- libs/mrwebrtc/src/interop/data_channel_interop.cpp
- libs/mrwebrtc/src/interop/global_factory.cpp
- libs/mrwebrtc/src/interop/global_factory.h
- libs/mrwebrtc/src/peer_connection.cpp
- libs/mrwebrtc/test/data_channel_tests.cpp
> Fix data channel issues

- libs/mrwebrtc/src/media/local_audio_track.h
- libs/mrwebrtc/src/media/local_video_track.h
- libs/mrwebrtc/src/media/remote_audio_track.h
- libs/mrwebrtc/src/media/remote_video_track.h
- libs/mrwebrtc/src/media/transceiver.cpp
- libs/mrwebrtc/src/refptr.h
Reviewing separately for clarity. See individual commit messages for description if needed.
> Minor changes and bug fixes

- tools/build/libwebrtc/build.sh
- tools/build/libwebrtc/checkout.sh
- tools/build/libwebrtc/config.sh
- tools/build/libwebrtc/lib.sh
- tools/ci/release-unity.yaml
- tools/ci/templates/jobs-libwebrtc-android.yaml
- tools/ci/templates/jobs-unity-package.yaml
- tools/ci/templates/steps-linux-clean-image.yaml
Add building the Android archive `mrwebrtc.aar` and packing it into the UPM package of the MixedReality-WebRTC Unity library.
> Add Android build to Unity release pipeline

- libs/unity/library/package.json
- libs/unity/samples/package.json
- tools/ci/computeNpmPackageVersion.ps1
This allows devs to import the package from disk.
> Use a correct version number in package.json

- examples/TestAppUwp/AddVideoTrackPage.xaml
- examples/TestAppUwp/ViewModel/VideoCaptureViewModel.cs
> Make video formats visible by default on HL

- tools/build/android/webrtc-native/src/main/cpp/CMakeLists.txt
Update `CMakeLists.txt` for the Android build.
> Fix CMakeLists.txt after recent changes

- tools/build/build.py
Enable building multiple configurations at once from the same command
call.
> Add support for multi-config build to build.py

- libs/unity/library/Runtime/Scripts/Media/MediaLine.cs
- libs/unity/library/Runtime/Scripts/Media/MediaReceiver.cs
- libs/unity/library/Runtime/Scripts/Media/WorkQueue.cs
- libs/unity/library/Tests/Runtime/MediaLineTests.cs
- libs/unity/library/Tests/Runtime/VideoSenderTests.cs
Limit Source and Receiver changes to main thread for simplicity.
> Fix edits of receiver pairing state

- libs/unity/samples/Runtime/Scenes/VideoChatDemo/VideoChatDemo.unity
References to some UI script had got corrupted along the way
> Fix VideoChatDemo scene

- libs/Microsoft.MixedReality.WebRTC/VideoFrameQueue.cs
> Release memory when clearing VideoFrameQueue

- docs/manual/cs/helloworld-cs-mediatracks-core3.md
- docs/manual/cs/helloworld-cs-setup-core3.md
- Fix typo and wrong method
- Recommend installing .NET 3.1, as 3.0 is end of life (EOL).
> Minor docs fixes

- libs/Microsoft.MixedReality.WebRTC/DataChannel.cs
- libs/mrwebrtc/include/data_channel_interop.h
> Document that data channel callbacks do not support reentrancy

- libs/mrwebrtc/src/media/device_video_track_source.cpp
Implement a custom video capture format enumeration based on
MediaCapture instead of relying on the broken webrtc-uwp-sdk
implementation, which is difficult to fix without some large refactor of
the video capturer.
This incidentally fixes #488 where a nullptr string was sometimes passed
to the std::string constructor leading to a crash. The offending code is
not used anymore.
Bug: #488, #492
> Work around broken getSupportedFormats() in UWP

- libs/unity/library/Runtime/Scripts/Android.cs
- libs/unity/library/Runtime/Scripts/Media/MicrophoneSource.cs
- libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
- libs/unity/library/Runtime/Scripts/Signaling/NodeDssSignaler.cs
Only use Android-specific code when not in editor. Do not use undocumented PLATFORM_ANDROID define.
> Fix Android-specific defines

- tools/build/build.py
- Ensure build.py is run from Python 3.x and not an earlier version,
before using 3.x features that make the script throw some cryptic error
- Add encoding to remove warning when running with Python 2.7
- Default to all targets/cpus if not specified, to avoid some cryptic
error if any of those is not provided
> Improve build.py

- libs/unity/library/Runtime/Scripts/Media/WebcamSource.cs
> Fix Unity build on Android

- libs/mrwebrtc/src/interop/interop_api.cpp
> Fix Win32 build

- libs/mrwebrtc/src/interop/interop_api.cpp
- libs/mrwebrtc/src/peer_connection.cpp
- libs/mrwebrtc/src/peer_connection.h
> Fix some Windows build

- tools/build/android/webrtc-native/src/main/java/com/microsoft/mixedreality/webrtc/AndroidCameraInterop.java
After this change you can change in c# which camera to use.
> Fix bug with comparing ids

- libs/mrwebrtc-unityplugin/src/log_helpers.cpp
- libs/mrwebrtc-unityplugin/src/log_helpers.h
- libs/mrwebrtc-unityplugin/src/pch.h
- tools/build/mrwebrtc-unityplugin/win32/mrwebrtc-unityplugin-win32.vcxproj
- Fix library path for Debug config to allow linker to find mrwebrtc.lib
- Move LogDebugString() into CPP and add missing headers to pch.h
- Add missing MR_UNITYPLUGIN_SHARING_WIN define in Debug config
- Fix some ClInclude XML tag in .vcxproj
> Fix Debug build of Unity native renderer

- README.md
- SUPPORT.md
Updated the readme.md file with our messaging about the project no longer being actively maintained, and added support.md per request from CSS
> Update Readme and create SUPPORT.MD
